packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  esbuild: true
  sharp: true
  workerd: true

peerDependencyRules:
  allowedVersions:
    eslint-plugin-react>eslint: "10"
    eslint-plugin-react-hooks>eslint: "10"
